### ISSUE TITLE
Individual Column Filtering

### ISSUE THREAD

**Issue by gjolund** [LumaPictures/meteor-jquery-datatables#5]
There are two column filtering options available : 
- [ Drilldown Widget ](http://www.datatables.net/extras/thirdparty/ColumnFilterWidgets/DataTables/extras/ColumnFilterWidgets/)
- [ Search Widget ](http://jquery-datatables-column-filter.googlecode.com/svn/trunk/index.html)

@stevenswanson would you mind weighing in and letting me know which you prefer, or both?

**Comment by NicoKnoll** [comment]
Same as @LDubya
